services:
  db:
    image: mysql:8.4.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: mission_note_de_frais
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/mysql

  smtp:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data: